### ISSUE TITLE
Studio UI 体验优化

### ISSUE THREAD

**Issue by fanjun-zy** [CloudCare/DataFlux-Roadmap#11]
切换场景的时候，鼠标移动到树状视图，这块很容易被挡住

![image](https://user-images.githubusercontent.com/53033320/101596689-80485f80-3a30-11eb-8c0f-614e5b57f091.png)

**Comment by Wendy1129** [comment]
谢谢反馈，场景的新建节点功能已经优化，本周四上线。#20

**Comment by Wendy1129** [comment]
已解决
