### ISSUE TITLE
Studio 视图优化(Y轴)

### ISSUE THREAD

**Issue by fanjun-zy** [CloudCare/DataFlux-Roadmap#12]
单位转换，Y轴没有换算

![image (1)](https://user-images.githubusercontent.com/53033320/101597106-30b66380-3a31-11eb-9d19-4b583d58f318.png)

**Comment by Wendy1129** [comment]
谢谢反馈，这个需求正在调研中。

**Comment by Wendy1129** [comment]
已上线。
