### ISSUE TITLE
DataKit 默认开启操作系统监控

### ISSUE THREAD

**Issue by fanjun-zy** [CloudCare/DataFlux-Roadmap#15]
在安装Datakit的时候，自动开启相应操作系统的监控插件
例如 Linux 自动开启 (cpu/disk/diskio/kernel/mem/processes/swap/system/net/netstat/net_response)插件

**Comment by Wendy1129** [comment]
谢谢反馈，这个需求已经在计划中。

**Comment by Wendy1129** [comment]
已增加主机监控默认配置，可直接通过“管理”-“数据网关”选择配置。
