### ISSUE TITLE
Studio 指标里标签/指标名太长无法完整显示

### ISSUE THREAD

**Issue by fanjun-zy** [CloudCare/DataFlux-Roadmap#19]
指标里标签/指标名太长无法完整显示，需要鼠标拖动到名字上才显示

<img width="281" alt="48627495-635F-493d-B749-6128D263274A" src="https://user-images.githubusercontent.com/53033320/101599045-0b772480-3a34-11eb-9223-983b07c3f580.png">

**Comment by Wendy1129** [comment]
谢谢反馈，指标名显示功能已经优化，本周四上线。

**Comment by Wendy1129** [comment]
功能已上线。
