### ISSUE TITLE
Studio 场景模板导入不显示背景图

### ISSUE THREAD

**Issue by fanjun-zy** [CloudCare/DataFlux-Roadmap#29]
场景模板导入不显示背景图，并且无法编辑

<img width="496" alt="AE37FA87-5C20-4886-B79F-32C2163AA63B" src="https://user-images.githubusercontent.com/53033320/102033759-2f9d8180-3df7-11eb-8edd-a6a7a682e329.png">

**Comment by Wendy1129** [comment]
谢谢反馈，已经在计划中，更新后会及时同步。

**Comment by Wendy1129** [comment]
已解决。
