### ISSUE TITLE
Studio 阿里云监控SLB部分数据无法正常采集

### ISSUE THREAD

**Issue by fanjun-zy** [CloudCare/DataFlux-Roadmap#33]
使用阿里云监控插件 (aliyuncms) 采集 SLB ，部分数据无法正常采集

<img width="813" alt="CE885C69-016A-4aea-ABB0-80A54396564E" src="https://user-images.githubusercontent.com/53033320/102160260-0eed2e80-3ec0-11eb-8109-beb43c580b73.png">

配置文件
[slb.txt](https://github.com/CloudCare/DataFlux-Roadmap/files/5692905/slb.txt)

**Comment by Wendy1129** [comment]
谢谢反馈，已经在调研中，更新后会及时同步。

**Comment by Wendy1129** [comment]
需要增加前置条件如http四层、七层协议、开启健康检查。
