### ISSUE TITLE
 日志模块标签提取问题

### ISSUE THREAD

**Issue by Py-Yf** [CloudCare/DataFlux-Roadmap#45]
日志模块提取标签创建es索引时,索引类型全部为string类型无法进行DQL计算分析
希望在提取标签时可以让用户自己手动指定每个提取字段的数据类型

**Comment by Wendy1129** [comment]
您的反馈已经收到，后期会进行优化处理，优化完成会同步您。#42

**Comment by Wendy1129** [comment]
日志模块的标签提取将通过采集器配置，预计本次迭代上线。

**Comment by Wendy1129** [comment]
标签提取已可以通过datakit配置，详情见如下网址：
https://help.dataflux.cn/doc/16554da77eddcb89fccaeb652e39f24f24ebaa2c
